import { NextPage } from 'next';
import Head from 'next/head';

import useTranslation from 'hooks/useTranslation';

import styles from '../styles/Temp.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.background}>
      <div className={styles.container}>
        <Head>
          <title>Vincent Pageaud | {useTranslation('mainTitle')}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
          <h1>Vincent Pageaud</h1>
          <h2>{useTranslation('mainTitle')}</h2>
          <a className={styles.button} href="https://www.linkedin.com/in/vincentpageaud/">
            LinkedIn
          </a>
          <a className={styles.button} href="https://www.malt.fr/profile/vincentpageaud">
            Malt
          </a>
        </header>
        <footer className={styles.footer}>This website is coming soon</footer>
      </div>
    </div>
  );
};

export default Home;
