import { NextPage } from 'next';
import Head from 'next/head';

import Header from 'components/Header/Header';
import Portfolio from 'components/Portfolio/Portfolio';

import useTranslation from 'hooks/useTranslation';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Vincent Pageaud | {useTranslation('mainTitle')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Portfolio />
    </>
  );
};

export default Home;
